name: Build and Release Flutter Desktop App

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Build for ${{ matrix.platform }}
        run: flutter build ${{ matrix.platform }} --release

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: setup_configs/windows.iss
          options: /O+

      - name: Archive build (Windows)
        if: matrix.platform == 'windows'
        run: |
          Compress-Archive -Path D:\a\mouse-moover\mouse-moover\build\windows\x64\runner\Release\* -DestinationPath mouse-moover-windows.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: mouse-moover-${{ matrix.platform }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
     # Scarica gli artifact da ciascun job
      - name: Download Windows Build
        uses: actions/download-artifact@v4
        with:
          name: windows
          path: ./build_artifacts/windows

      # Crea la release usando il tag corrente
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Se preferisci utilizzare un tag specifico, assicurati che venga creato
          tag_name: ${{ github.sha }}
          name: "Release ${{ github.sha }}"
          draft: false
          prerelease: false

      # Carica l'asset nella release
      - name: Upload Windows Release Asset
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: upload ./build_artifacts/windows/mouse-moover-windows.zip
