name: Build and Release Flutter Desktop App

on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
          - os: macos-latest
            platform: macos
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2.19.0
        with:
          channel: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Build for ${{ matrix.platform }}
        run: flutter build ${{ matrix.platform }} --release

      - name: Build Windows Installer
        if: matrix.platform == 'windows'
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.5
        with:
          path: setup_configs/windows.iss
          options: /O+

      - name: Upload Windows Installer
        if: matrix.platform == 'windows'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-installer
          path: D:\a\mouse-moover\mouse-moover\build\windows\x64\runner\Release\Mouse_Moover_Setup.exe

      - name: Build MacOS Installer
        if: matrix.platform == 'macos'
        uses: L-Super/create-dmg-actions@v1.0.3
        with:
          dmg_name: ${{ matrix.platform }}-installer
          src_dir: build/macos/Build/Products/Release/mouse_moover.app

      - name: Upload MacOS Installer
        if: matrix.platform == 'macos'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-installer
          path: /Users/runner/work/mouse-moover/mouse-moover/macos-installer.dmg

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
        # Scarica gli artifact da ciascun job
      - name: Download Windows Build
        uses: actions/download-artifact@v4
        with:
          name: windows-installer
          path: ./build_artifacts/windows

      - name: Download macOS Build
        uses: actions/download-artifact@v4
        with:
          name: macos-installer
          path: ./build_artifacts/macos

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fetch_all_tags: true
          
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.16.0
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          artifacts: "build_artifacts/windows/*,build_artifacts/macos/*"